import type { Customer, Activity, SalesRep, Route } from '../types';
import { subDays, subHours } from 'date-fns';

const now = new Date();

export const SALES_REPS: SalesRep[] = [
  { id: 'rep1', name: 'Lipa Cohen', role: 'admin', territory: 'Brooklyn', email: 'lipa@sunlite.com', avatarInitials: 'LC' },
  { id: 'rep2', name: 'David Stern', role: 'field_sales', territory: 'Queens', email: 'david@sunlite.com', avatarInitials: 'DS' },
  { id: 'rep3', name: 'Sarah Klein', role: 'inside_sales', territory: 'Manhattan', email: 'sarah@sunlite.com', avatarInitials: 'SK' },
  { id: 'rep4', name: 'Mike Rosen', role: 'customer_service', territory: 'Bronx', email: 'mike@sunlite.com', avatarInitials: 'MR' },
];

export const CUSTOMERS: Customer[] = [
  {
    id: 'BU000001',
    name: 'Budget Maintenance',
    assignedRepId: 'rep1',
    assignedRepName: 'Lipa Cohen',
    territory: 'Brooklyn',
    city: '', state: '', billingAddress: '1542 Flatbush Ave, Brooklyn, NY 11210',
    phone: '(718) 555-0101',
    email: 'orders@budgetmaintenance.com',
    priorityTier: 1,
    customerClass: 'Hardware',
    visitFrequency: 'biweekly',
    lastContactDate: subDays(now, 32).toISOString(),
    activeStatus: true,
    openOrderCount: 3,
    revenue: 145000, revenueByQuarter: {},
    dayOfWeek: 2,
  },
  {
    id: 'BO000002',
    name: 'Boro Park Lumber',
    assignedRepId: 'rep1',
    assignedRepName: 'Lipa Cohen',
    territory: 'Brooklyn',
    city: '', state: '', billingAddress: '4820 13th Ave, Brooklyn, NY 11219',
    phone: '(718) 555-0202',
    email: 'info@boroparklumber.com',
    priorityTier: 2,
    customerClass: 'Lumber',
    visitFrequency: 'weekly',
    lastContactDate: subDays(now, 5).toISOString(),
    activeStatus: true,
    openOrderCount: 7,
    revenue: 312000, revenueByQuarter: {},
    dayOfWeek: 2,
  },
  {
    id: 'SAI00001',
    name: 'Saifee Hardware',
    assignedRepId: 'rep1',
    assignedRepName: 'Lipa Cohen',
    territory: 'Brooklyn',
    city: '', state: '', billingAddress: '786 Atlantic Ave, Brooklyn, NY 11238',
    phone: '(718) 555-0303',
    email: 'saifee@hardware.com',
    priorityTier: 2,
    customerClass: 'Hardware',
    visitFrequency: 'biweekly',
    lastContactDate: subDays(now, 12).toISOString(),
    activeStatus: true,
    openOrderCount: 2,
    revenue: 89000, revenueByQuarter: {},
    dayOfWeek: 2,
  },
  {
    id: 'CER00002',
    name: 'Certified Lumber',
    assignedRepId: 'rep2',
    assignedRepName: 'David Stern',
    territory: 'Queens',
    city: '', state: '', billingAddress: '112-05 Jamaica Ave, Queens, NY 11418',
    phone: '(718) 555-0404',
    email: 'orders@certifiedlumber.com',
    priorityTier: 1,
    customerClass: 'Lumber',
    visitFrequency: 'biweekly',
    lastContactDate: subDays(now, 8).toISOString(),
    activeStatus: true,
    openOrderCount: 5,
    revenue: 278000, revenueByQuarter: {},
    dayOfWeek: 2,
  },
  {
    id: 'FLU00003',
    name: 'Flushing Supply Co',
    assignedRepId: 'rep2',
    assignedRepName: 'David Stern',
    territory: 'Queens',
    city: '', state: '', billingAddress: '37-12 Main St, Flushing, NY 11354',
    phone: '(718) 555-0505',
    email: 'contact@flushingsupply.com',
    priorityTier: 3,
    customerClass: 'Plumbing',
    visitFrequency: 'monthly',
    lastContactDate: subDays(now, 35).toISOString(),
    activeStatus: true,
    openOrderCount: 1,
    revenue: 54000, revenueByQuarter: {},
    dayOfWeek: 3,
  },
  {
    id: 'AST00004',
    name: 'Astoria Hardware',
    assignedRepId: 'rep2',
    assignedRepName: 'David Stern',
    territory: 'Queens',
    city: '', state: '', billingAddress: '21-45 31st St, Astoria, NY 11105',
    phone: '(718) 555-0606',
    email: 'astoria@hardware.net',
    priorityTier: 3,
    customerClass: 'Hardware',
    visitFrequency: 'monthly',
    lastContactDate: subDays(now, 18).toISOString(),
    activeStatus: true,
    openOrderCount: 0,
    revenue: 41000, revenueByQuarter: {},
    dayOfWeek: 4,
  },
  {
    id: 'MAN00005',
    name: 'Manhattan Tool & Supply',
    assignedRepId: 'rep3',
    assignedRepName: 'Sarah Klein',
    territory: 'Manhattan',
    city: '', state: '', billingAddress: '245 W 29th St, New York, NY 10001',
    phone: '(212) 555-0707',
    email: 'tools@manhattansupply.com',
    priorityTier: 1,
    customerClass: 'Tools',
    visitFrequency: 'weekly',
    lastContactDate: subDays(now, 3).toISOString(),
    activeStatus: true,
    openOrderCount: 9,
    revenue: 520000, revenueByQuarter: {},
    dayOfWeek: 1,
  },
  {
    id: 'HAR00006',
    name: 'Harlem Building Materials',
    assignedRepId: 'rep3',
    assignedRepName: 'Sarah Klein',
    territory: 'Manhattan',
    city: '', state: '', billingAddress: '2250 Adam Clayton Powell Jr Blvd, NY 10027',
    phone: '(212) 555-0808',
    email: 'hbm@buildingmaterials.com',
    priorityTier: 2,
    customerClass: 'Building Materials',
    visitFrequency: 'biweekly',
    lastContactDate: subDays(now, 40).toISOString(),
    activeStatus: true,
    openOrderCount: 4,
    revenue: 167000, revenueByQuarter: {},
    dayOfWeek: 1,
  },
  {
    id: 'BRX00007',
    name: 'Bronx Pro Hardware',
    assignedRepId: 'rep4',
    assignedRepName: 'Mike Rosen',
    territory: 'Bronx',
    city: '', state: '', billingAddress: '880 E Tremont Ave, Bronx, NY 10460',
    phone: '(718) 555-0909',
    email: 'bronxpro@hardware.com',
    priorityTier: 3,
    customerClass: 'Hardware',
    visitFrequency: 'monthly',
    lastContactDate: subDays(now, 25).toISOString(),
    activeStatus: true,
    openOrderCount: 2,
    revenue: 72000, revenueByQuarter: {},
    dayOfWeek: 5,
  },
  {
    id: 'WIL00008',
    name: 'Williamsburg Fasteners',
    assignedRepId: 'rep1',
    assignedRepName: 'Lipa Cohen',
    territory: 'Brooklyn',
    city: '', state: '', billingAddress: '318 Bedford Ave, Brooklyn, NY 11211',
    phone: '(718) 555-1010',
    email: 'wfasteners@bk.net',
    priorityTier: 4,
    customerClass: 'Fasteners',
    visitFrequency: 'monthly',
    lastContactDate: subDays(now, 45).toISOString(),
    activeStatus: true,
    openOrderCount: 0,
    revenue: 28000, revenueByQuarter: {},
    dayOfWeek: 4,
  },
  {
    id: 'JAM00009',
    name: 'Jamaica Electrical Supply',
    assignedRepId: 'rep2',
    assignedRepName: 'David Stern',
    territory: 'Queens',
    city: '', state: '', billingAddress: '165-10 Jamaica Ave, Jamaica, NY 11432',
    phone: '(718) 555-1111',
    email: 'jes@electricalsupply.com',
    priorityTier: 2,
    customerClass: 'Electrical',
    visitFrequency: 'biweekly',
    lastContactDate: subDays(now, 9).toISOString(),
    activeStatus: true,
    openOrderCount: 6,
    revenue: 195000, revenueByQuarter: {},
    dayOfWeek: 3,
  },
  {
    id: 'STA00010',
    name: 'Staten Island Lumber Depot',
    assignedRepId: 'rep4',
    assignedRepName: 'Mike Rosen',
    territory: 'Staten Island',
    city: '', state: '', billingAddress: '2685 Richmond Ave, Staten Island, NY 10314',
    phone: '(718) 555-1212',
    email: 'sild@lumberdepot.com',
    priorityTier: 4,
    customerClass: 'Lumber',
    visitFrequency: 'monthly',
    lastContactDate: subDays(now, 28).toISOString(),
    activeStatus: true,
    openOrderCount: 1,
    revenue: 38000, revenueByQuarter: {},
    dayOfWeek: 5,
  },
];

export const ACTIVITIES: Activity[] = [
  { id: 'a1', customerId: 'BU000001', type: 'visit', date: subDays(now, 32).toISOString(), repName: 'Lipa Cohen', summary: 'Dropped by, spoke with manager about Q3 order volumes. They plan to increase fastener orders by 20%.' },
  { id: 'a2', customerId: 'BU000001', type: 'call', date: subDays(now, 15).toISOString(), repName: 'Lipa Cohen', summary: 'Follow-up call regarding pending invoice #INV-2024-441. Payment confirmed for next week.' },
  { id: 'a3', customerId: 'BU000001', type: 'note', date: subDays(now, 5).toISOString(), repName: 'Mike Rosen', summary: 'Customer requested updated catalog pricing for power tools.' },
  { id: 'a4', customerId: 'BO000002', type: 'visit', date: subDays(now, 5).toISOString(), repName: 'Lipa Cohen', summary: 'Weekly check-in. Reviewed current lumber order. Need to verify cedar stock availability.' },
  { id: 'a5', customerId: 'BO000002', type: 'call', date: subDays(now, 12).toISOString(), repName: 'Lipa Cohen', summary: 'Discussed upcoming spring sale pricing. Will send updated price sheet by EOW.' },
  { id: 'a6', customerId: 'BO000002', type: 'email', date: subDays(now, 3).toISOString(), repName: 'System', summary: '[Auto-Logged via Gmail] Customer inquired about delivery window for Order #SO-8842, requesting confirmation by Thursday. Tone is professional and not urgent.', source: 'gmail-auto' },
  { id: 'a7', customerId: 'SAI00001', type: 'visit', date: subDays(now, 12).toISOString(), repName: 'Lipa Cohen', summary: 'Met with owner Saifee. Reviewed planogram for hand tool section. New display agreed upon.' },
  { id: 'a8', customerId: 'SAI00001', type: 'note', date: subDays(now, 8).toISOString(), repName: 'Sarah Klein', summary: 'Customer requested quote for bulk drill bits — 500 units, 1/4 inch and 3/8 inch mix.' },
  { id: 'a9', customerId: 'CER00002', type: 'visit', date: subDays(now, 8).toISOString(), repName: 'David Stern', summary: 'Bi-weekly visit. Walked the floor. Noticed low stock on 2x4 — placed emergency reorder.' },
  { id: 'a10', customerId: 'CER00002', type: 'call', date: subDays(now, 2).toISOString(), repName: 'David Stern', summary: 'Quick call to confirm delivery of emergency reorder. Scheduled for tomorrow AM.' },
  { id: 'a11', customerId: 'MAN00005', type: 'visit', date: subDays(now, 3).toISOString(), repName: 'Sarah Klein', summary: 'Weekly account visit. Reviewed Q4 purchasing plan. Large Milwaukee Tool order incoming.' },
  { id: 'a12', customerId: 'MAN00005', type: 'email', date: subHours(now, 6).toISOString(), repName: 'System', summary: '[Auto-Logged via Gmail] Account manager sent RFQ for 200 units of cordless drill sets and 50 units of reciprocating saws. Budget confirmed. Requesting best pricing.', source: 'gmail-auto' },
  { id: 'a13', customerId: 'HAR00006', type: 'call', date: subDays(now, 40).toISOString(), repName: 'Sarah Klein', summary: 'Initial call after assignment. Customer was cold — mentioned they prefer in-person visits.' },
  { id: 'a14', customerId: 'FLU00003', type: 'visit', date: subDays(now, 35).toISOString(), repName: 'David Stern', summary: 'Monthly check-in. Slower month — down 15% from prior month. Will follow up with promo offer.' },
  { id: 'a15', customerId: 'WIL00008', type: 'note', date: subDays(now, 45).toISOString(), repName: 'Lipa Cohen', summary: 'No activity since last visit. Need to re-engage. Try calling first week of next month.' },
];

export const ROUTES: Route[] = CUSTOMERS.map(c => ({
  customerId: c.id,
  frequency: c.visitFrequency,
  lastVisitDate: c.lastContactDate,
  dayOfWeek: c.dayOfWeek,
}));

export const QUICK_LINKS = [
  { id: 'ql1', label: 'Product Catalog', icon: 'BookOpen', description: 'Full product catalog & specs', url: '#' },
  { id: 'ql2', label: 'Price Sheet', icon: 'DollarSign', description: 'Current pricing by category', url: '#' },
  { id: 'ql3', label: 'Order Entry', icon: 'ShoppingCart', description: 'Acumatica order entry portal', url: '#' },
  { id: 'ql4', label: 'Internal Docs', icon: 'FileText', description: 'Policies, SOPs, and training', url: '#' },
  { id: 'ql5', label: 'Territory Map', icon: 'Map', description: 'Rep territory boundaries', url: '#' },
  { id: 'ql6', label: 'CRM Reports', icon: 'BarChart2', description: 'Sales activity reports', url: '#' },
  { id: 'ql7', label: 'Sample Requests', icon: 'Package', description: 'Request product samples', url: '#' },
  { id: 'ql8', label: 'Support Desk', icon: 'Headphones', description: 'Internal IT & ops support', url: '#' },
];
